name: kmis
channels:
  - anaconda
  - conda-forge
  - ipython
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astor=0.8.1
  - ca-certificates=2020.10.14
  - certifi=2021.5.30
  - cudatoolkit=10.2.89
  - freetype=2.11.0
  - jpeg=9d
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - ncurses=6.3
  - olefile=0.46
  - openssl=1.1.1m
  - patchelf=0.10
  - pillow=8.0.0
  - pyparsing=2.4.7
  - python=3.6.10
  - python-dateutil=2.8.1
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - numpy==1.19
    - pandas
    - joblib==0.17.0
    - markdown
    - matplotlib==3.3
    - rsa==4.8
    - scikit-learn==0.24.2
    - scipy==1.5
    - seaborn
    - h5py==2.10.0
    - cloudpickle==1.6.0
    - dataclasses==0.8
    - decorator==5.1.1
    - tqdm
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - tensorflow-probability==0.7.0
    - wandb==0.12
    - absl-py==0.10.0
    - autograd==1.3
    - charset-normalizer==2.0.12
    - click==8.0.4
    - docker-pycreds==0.4.0
    - future==0.18.2
    - gast==0.2.2
    - gitdb==4.0.9
    - gitpython==3.1.18
    - google-pasta==0.2.0
    - grpcio==1.36.1
    - idna==3.3
    - importlib-metadata==4.8.3
    - ipython==7.16.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - mypy-extensions==0.4.3
    - numdifftools==0.9.39
    - pathtools==0.1.2
    - pingouin
    - promise==2.3
    - protobuf==3.13.0
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyglet==1.5.0
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - yaspin==2.1.0
    - zipp==3.6.0
